module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 50],
    'body-max-line-length': [2, 'always', 80],
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'test', 'docs', 'chore'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'addsections',
        'agents',
        'app',
        'applayout',
        'certifications',
        'ci',
        'components',
        'e2e',
        'education',
        'eslint',
        'experience',
        'hooks',
        'husky',
        'jest',
        'links',
        'navbar',
        'package',
        'pages',
        'personal',
        'preview',
        'projects',
        'readme',
        'sidebar',
        'skills',
        'styles',
        'toolbar',
        'types',
        'utils',
        'webpack',
      ],
    ],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-case': [0],
  },
};
